"""Add pstrax_base_url to ScrapeConfig

Revision ID: 20250101_000000
Revises: 
Create Date: 2025-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250101_000000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Check if column already exists (for cases where db.create_all() was used)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('scrape_config')]
    
    if 'pstrax_base_url' not in columns:
        # Add column with default value
        op.add_column('scrape_config', 
                     sa.Column('pstrax_base_url', sa.String(length=255), 
                              nullable=False, 
                              server_default='https://pstrax.com'))
        
        # Update existing rows to have the default value
        op.execute("UPDATE scrape_config SET pstrax_base_url = 'https://pstrax.com' WHERE pstrax_base_url IS NULL")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_config', 'pstrax_base_url')
    # ### end Alembic commands ###

