"""Add priority field to tasks

Revision ID: 0b088bb68db2
Revises: 947ba3cedf70
Create Date: 2025-11-03 15:07:23.913310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b088bb68db2'
down_revision = '947ba3cedf70'
branch_labels = None
depends_on = None


def upgrade():
    # Add priority column as nullable first (SQLite requirement)
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
    
    # Set default priority (2 = Medium) for existing tasks
    op.execute("UPDATE task SET priority = 2 WHERE priority IS NULL")
    
    # Now make the column NOT NULL
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('priority', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
